-- Stable structured errors for the strict global GameSave schema and its
-- catalog operations. Pure domain code: no LÖVE or filesystem dependency.

local GameSaveErrors = {}

GameSaveErrors.GAME_SAVE_INVALID = "GAME_SAVE_INVALID"
GameSaveErrors.GAME_SAVE_SCHEMA_UNSUPPORTED = "GAME_SAVE_SCHEMA_UNSUPPORTED"
GameSaveErrors.GAME_SAVE_SAVE_ID_INVALID = "GAME_SAVE_SAVE_ID_INVALID"
GameSaveErrors.GAME_SAVE_SAVE_ID_MISMATCH = "GAME_SAVE_SAVE_ID_MISMATCH"
GameSaveErrors.GAME_SAVE_VERSION_INVALID = "GAME_SAVE_VERSION_INVALID"
GameSaveErrors.GAME_SAVE_PLAY_TIME_INVALID = "GAME_SAVE_PLAY_TIME_INVALID"
GameSaveErrors.GAME_SAVE_FIELD_INVALID = "GAME_SAVE_FIELD_INVALID"
GameSaveErrors.GAME_SAVE_BUCKET_INVALID = "GAME_SAVE_BUCKET_INVALID"
GameSaveErrors.GAME_SAVE_CATALOG_INVALID = "GAME_SAVE_CATALOG_INVALID"
GameSaveErrors.GAME_SAVE_NOT_RESERVED = "GAME_SAVE_NOT_RESERVED"
GameSaveErrors.GAME_SAVE_ALREADY_PUBLISHED = "GAME_SAVE_ALREADY_PUBLISHED"
GameSaveErrors.GAME_SAVE_NOT_PUBLISHED = "GAME_SAVE_NOT_PUBLISHED"

return GameSaveErrors
