-- Error codes for HGSS asset adaptation and semantic audio policy.

local AudioErrors = {}

AudioErrors.AUDIO_PROVIDER_INDEX_UNAVAILABLE = "AUDIO_PROVIDER_INDEX_UNAVAILABLE"
AudioErrors.AUDIO_PROVIDER_SEQUENCE_UNKNOWN = "AUDIO_PROVIDER_SEQUENCE_UNKNOWN"
AudioErrors.AUDIO_PROVIDER_BANK_UNKNOWN = "AUDIO_PROVIDER_BANK_UNKNOWN"
AudioErrors.AUDIO_PROVIDER_PLAYER_UNKNOWN = "AUDIO_PROVIDER_PLAYER_UNKNOWN"
AudioErrors.AUDIO_PROVIDER_SAMPLE_UNKNOWN = "AUDIO_PROVIDER_SAMPLE_UNKNOWN"

AudioErrors.AUDIO_CRY_UNAVAILABLE = "AUDIO_CRY_UNAVAILABLE"
AudioErrors.AUDIO_MAP_MUSIC_UNAVAILABLE = "AUDIO_MAP_MUSIC_UNAVAILABLE"
AudioErrors.AUDIO_SAVE_INVALID = "AUDIO_SAVE_INVALID"

return AudioErrors
