FROM ghcr.io/gflorio/agentbox:latest

USER root
RUN apt-get update \
    && add-apt-repository --yes ppa:bartbes/love-stable \
    && apt-get update \
    && apt-get install -y --no-install-recommends love \
    && rm -rf /var/lib/apt/lists/*
USER 1000:1000
