-- Script translation pipeline tests: decode a synthetic member, lower,
-- structure, verify, and emit the DSL resource, with
-- deterministic emission and coverage accounting. No ROM and no decomp
-- checkout required.

local Assert = require("tests.support.Assert")
local ScriptFixture = require("tests.support.ScriptFixture")
local ScriptBinaryDecoder = require("romdump.src.digest.script.ScriptBinaryDecoder")
local SemanticLowering = require("romdump.src.digest.script.SemanticLowering")
local Structurer = require("romdump.src.digest.script.Structurer")
local LuaEmitter = require("romdump.src.digest.script.LuaEmitter")
local Verifier = require("romdump.src.digest.script.Verifier")
local Coverage = require("romdump.src.digest.script.Coverage")
local SourceCatalog = require("romdump.src.digest.script.SourceCatalog")
local S = require("gen4.script")

local T = {}

local CATALOG = {
  sounds = { [1500] = "SEQ_SE_DP_SELECT" },
  flags = { [0x6A] = "FLAG_GOT_STARTER" },
  vars = { [0x8008] = "VAR_SPECIAL_x8008" },
  maps = {},
}

-- The lab-sign shape (member 843 script 9): PlaySE; LockAll; NPCMsg 97;
-- WaitButton; CloseMsg; ReleaseAll; End.
local function labSignMember()
  return ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          { op = 73, args = { { value = 1500, width = 2 } } },
          { op = 96, args = {} },
          { op = 45, args = { { value = 97, width = 1 } } },
          { op = 50, args = {} },
          { op = 53, args = {} },
          { op = 97, args = {} },
          { op = 2, args = {} },
        },
      },
    },
  })
end

local function translate(bytes, member, scriptIndex)
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, member, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[scriptIndex], ir, { stdCatalog = SourceCatalog.catalog() })
  local steps = Structurer.structure(lowered, scriptIndex)
  local report = Verifier.verifyScript(lowered, ir.scripts[scriptIndex], ir)
  local function scrub(items)
    for _, item in ipairs(items) do
      if item.op == "if" then
        scrub(item.yes)
        scrub(item.no)
      end
      item.movementComplete = nil
      item.movementUnsupported = nil
      item.sourceFacing = nil
      item.yieldsNextTick = nil
      item.sourceNotes = nil
    end
  end
  scrub(steps)
  return ir, steps, report
end

-- 1. The lab-sign sequence lowers to the canonical fold shape.
T["lab sign fold shape"] = function()
  local _, steps, report = translate(labSignMember(), 843, 0)
  local ops = {}
  for _, step in ipairs(steps) do
    ops[#ops + 1] = step.op
  end
  Assert.deepEqual(ops, { "play_sound", "lock_all", "say", "release_all", "yield_tick", "stop" })
  Assert.equal(steps[1].sound, "SEQ_SE_DP_SELECT")
  Assert.equal(steps[3].message, "msg.hgss.0543.00097")
  Assert.isTrue(report.complete)
end

-- 2. Emission is deterministic and byte-stable, and the resource validates.
T["emitter determinism and validation"] = function()
  local _, steps, report = translate(labSignMember(), 843, 0)
  local resource = {
    api = 1,
    id = "new_bark.lab_sign",
    metadata = { coverage = { complete = report.complete, unsupportedCount = report.unsupportedCount } },
    steps = steps,
  }
  local meta = {
    member = 843,
    scriptIndex = 9,
    sourcePath = "romfs/scr_seq.narc",
    commit = "rom-sha",
    repository = "g4recomp",
    game = "heartgold",
    sourceHash = "member-sha",
    coverage = resource.metadata.coverage,
  }
  Assert.equal(LuaEmitter.emit(resource, meta), LuaEmitter.emit(resource, meta))
  local text = LuaEmitter.emit(resource, meta)
  Assert.equal(text:sub(-1), "\n")
  Assert.isTrue(text:find("Generated by hgss-script-translator", 1, true) ~= nil)
  Assert.isTrue(text:find("msg.hgss.0543.00097", 1, true) ~= nil)
  Assert.isTrue(text:find('game = "heartgold"', 1, true) ~= nil)
  local ok, validateErr = S.validate(resource)
  Assert.isTrue(ok, tostring(validateErr))
end

-- 3. An unsupported instruction (e.g. SetTrainerFlag) makes the script
-- partial with an explicit unsupported node.
T["unsupported instructions stay explicit"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          { op = 36, args = { { value = 1, width = 2 }, { value = 2, width = 2 } } },
          { op = 2, args = {} },
        },
      },
    },
  })
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 5, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  Assert.equal(#lowered.unsupported, 1)
  Assert.equal(lowered.unsupported[1].command, 36)
  Assert.equal(lowered.unsupported[1].originalName, "ScrCmd_SetTrainerFlag")
  local report = Verifier.verifyScript(lowered, ir.scripts[0], ir)
  Assert.isFalse(report.complete)
  Assert.equal(report.unsupportedCount, 1)
end

-- 4. The coverage record aggregates occurrence counts with the pinned names.
T["coverage record counts opcodes"] = function()
  local ir =
    assert(ScriptBinaryDecoder.parseMember(labSignMember(), 843, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  local steps = Structurer.structure(lowered, 0)
  local report = Verifier.verifyScript(lowered, ir.scripts[0], ir)
  local record = Coverage.record(ir, {
    [0] = { script = ir.scripts[0], resource = { id = "x" }, report = report },
  }, { repository = "g4recomp", commit = "rom-sha" })
  Assert.equal(record.totals.scripts, 1)
  Assert.equal(record.totals.reachableInstructions, 7)
  Assert.equal(record.opcodes[73].name, "ScrCmd_PlaySE")
  Assert.equal(record.opcodes[73].occurrences, 1)
  Assert.equal(record.opcodes[45].name, "ScrCmd_NPCMsg")
  Assert.equal(record.scripts[1].status, "complete")
  Assert.isTrue(Coverage.markdown(record):find("ScrCmd_PlaySE", 1, true) ~= nil)
end

-- 5. The std catalog resolves CallStd operands to common.<name> ids.
T["call std resolves common ids"] = function()
  local catalog = SourceCatalog.catalog()
  local name = SourceCatalog.commonPublicId(catalog, 0x30A)
  Assert.isTrue(name == "common.std_" .. tostring(0x30A) or name:match("^common%.") ~= nil)
  Assert.equal(catalog.locate(2000).member, 3)
  Assert.equal(catalog.locate(2000).scriptIndex, 0)
end

return T
