-- Script translation pipeline tests: decode a synthetic member, lower,
-- structure, verify, and emit the DSL resource, with
-- deterministic emission and coverage accounting. No ROM and no decomp
-- checkout required.

local Assert = require("tests.support.Assert")
local ScriptFixture = require("tests.support.ScriptFixture")
local ScriptBinaryDecoder = require("romdump.src.digest.script.ScriptBinaryDecoder")
local SemanticLowering = require("romdump.src.digest.script.SemanticLowering")
local Structurer = require("romdump.src.digest.script.Structurer")
local LuaEmitter = require("romdump.src.digest.script.LuaEmitter")
local Verifier = require("romdump.src.digest.script.Verifier")
local Coverage = require("romdump.src.digest.script.Coverage")
local SourceCatalog = require("romdump.src.digest.script.SourceCatalog")
local CommandCatalog = require("romdump.src.digest.script.CommandCatalog")
local S = require("gen4.script")

local T = {}

-- Script-cache invalidation is owned by the producer fingerprint: any edit
-- under romdump/src (including semantic-lowering changes) changes the
-- fingerprint and forces a full derived rebuild (producer_fingerprint_test +
-- cache_builder_test's forced-rebuild case). The old per-compiler
-- COMPILER_VERSION pin is gone with the constant.

local CATALOG = {
  sounds = { [1500] = "SEQ_SE_DP_SELECT" },
  flags = { [0x6A] = "FLAG_GOT_STARTER" },
  vars = { [0x8008] = "VAR_SPECIAL_x8008" },
  maps = {},
}

-- The lab-sign shape (member 843 script 9): PlaySE; LockAll; NPCMsg 97;
-- WaitButton; CloseMsg; ReleaseAll; End.
local function labSignMember()
  return ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          { op = 73, args = { { value = 1500, width = 2 } } },
          { op = 96, args = {} },
          { op = 45, args = { { value = 97, width = 1 } } },
          { op = 50, args = {} },
          { op = 53, args = {} },
          { op = 97, args = {} },
          { op = 2, args = {} },
        },
      },
    },
  })
end

local function translate(bytes, member, scriptIndex)
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, member, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[scriptIndex], ir, { stdCatalog = SourceCatalog.catalog() })
  local steps = Structurer.structure(lowered, scriptIndex)
  local function scrub(items)
    for _, item in ipairs(items) do
      if item.op == "if" then
        scrub(item.yes)
        scrub(item.no)
      end
      item.movementComplete = nil
      item.movementUnsupported = nil
      item.yieldsNextTick = nil
      item.sourceNotes = nil
    end
  end
  scrub(steps)
  local report = Verifier.verifyScript(steps, ir.scripts[scriptIndex], ir, lowered.omissions)
  return ir, steps, report
end

-- 1. The lab-sign sequence lowers to the canonical fold shape.
T["lab sign fold shape"] = function()
  local _, steps, report = translate(labSignMember(), 843, 0)
  local ops = {}
  for _, step in ipairs(steps) do
    ops[#ops + 1] = step.op
  end
  Assert.deepEqual(ops, { "play_sound", "lock_all", "say", "release_all", "yield_tick", "stop" })
  Assert.equal(steps[1].sound, "SEQ_SE_DP_SELECT")
  Assert.equal(steps[3].message, "msg.hgss.0543.00097")
  Assert.isTrue(report.complete)
end

-- 2. Emission is deterministic and byte-stable, and the resource validates.
T["emitter determinism and validation"] = function()
  local _, steps, report = translate(labSignMember(), 843, 0)
  local resource = {
    api = 1,
    id = "new_bark.lab_sign",
    metadata = { coverage = { complete = report.complete, unsupportedCount = report.unsupportedCount } },
    steps = steps,
  }
  local meta = {
    member = 843,
    scriptIndex = 9,
    sourcePath = "romfs/scr_seq.narc",
    romSha1 = "rom-sha",
    repository = "g4recomp",
    game = "heartgold",
    sourceHash = "member-sha",
    coverage = resource.metadata.coverage,
  }
  Assert.equal(LuaEmitter.emit(resource, meta), LuaEmitter.emit(resource, meta))
  local text = LuaEmitter.emit(resource, meta)
  Assert.equal(text:sub(-1), "\n")
  Assert.isTrue(text:find("Generated by hgss-script-translator", 1, true) ~= nil)
  Assert.isTrue(text:find("msg.hgss.0543.00097", 1, true) ~= nil)
  Assert.isTrue(text:find('game = "heartgold"', 1, true) ~= nil)
  local ok, validateErr = S.validate(resource)
  Assert.isTrue(ok, tostring(validateErr))
end

-- 3. An unsupported instruction (e.g. SetTrainerFlag) makes the script
-- partial with an explicit unsupported node.
T["unsupported instructions stay explicit"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          { op = 36, args = { { value = 1, width = 2 }, { value = 2, width = 2 } } },
          { op = 2, args = {} },
        },
      },
    },
  })
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 5, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  Assert.equal(#lowered.unsupported, 1)
  Assert.equal(lowered.unsupported[1].command, 36)
  Assert.equal(lowered.unsupported[1].originalName, "ScrCmd_SetTrainerFlag")
  local report = Verifier.verifyScript(Structurer.structure(lowered, 0), ir.scripts[0], ir, lowered.omissions)
  Assert.isFalse(report.complete)
  Assert.equal(report.unsupportedCount, 1)
end

-- 4. The coverage record aggregates occurrence counts with the pinned names.
T["coverage record counts opcodes"] = function()
  local ir =
    assert(ScriptBinaryDecoder.parseMember(labSignMember(), 843, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  local steps = Structurer.structure(lowered, 0)
  local report = Verifier.verifyScript(steps, ir.scripts[0], ir, lowered.omissions)
  local record = Coverage.record(ir, {
    [0] = { script = ir.scripts[0], resource = { id = "x" }, report = report },
  }, { repository = "g4recomp", romSha1 = "rom-sha" })
  Assert.equal(record.totals.scripts, 1)
  Assert.equal(record.totals.reachableInstructions, 7)
  Assert.equal(record.opcodes[73].name, "ScrCmd_PlaySE")
  Assert.equal(record.opcodes[73].occurrences, 1)
  Assert.equal(record.opcodes[45].name, "ScrCmd_NPCMsg")
  Assert.equal(record.scripts[1].status, "complete")
  Assert.isTrue(Coverage.markdown(record):find("ScrCmd_PlaySE", 1, true) ~= nil)
end

-- 5. The std catalog resolves CallStd operands to common.<name> ids.
T["call std resolves common ids"] = function()
  local catalog = SourceCatalog.catalog()
  local name = SourceCatalog.commonPublicId(catalog, 0x30A)
  Assert.isTrue(name == "common.std_" .. tostring(0x30A) or name:match("^common%.") ~= nil)
  Assert.equal(catalog.locate(2000).member, 3)
  Assert.equal(catalog.locate(2000).scriptIndex, 0)
end

-- 6. A conditional call is never peeled into a branch region: the emitted
-- program keeps the structured if wrapping the call.
T["call_if stays a structured call"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          -- 0x20: compare (6 bytes) -> 0x26
          { op = 17, args = { { value = 1, width = 2 }, { value = 2, width = 2 } } },
          -- 0x26: CallIf (7 bytes) -> 0x2D, target 0x33 (the subroutine entry)
          { op = 29, args = { { value = 1, width = 1 }, { target = 0x33, width = 4 } } },
          -- 0x2D: SetFlag (4 bytes) -> 0x31
          { op = 30, args = { { value = 3, width = 2 } } },
          -- 0x31: End (2 bytes) -> 0x33
          { op = 2, args = {} },
          -- 0x33: subroutine entry (branch target label), SetFlag (4) -> 0x37
          { op = 30, args = { { value = 4, width = 2 } } },
          -- 0x37: Return (2 bytes) -> 0x39
          { op = 27, args = {} },
        },
      },
    },
  })
  local _, steps = translate(bytes, 5, 0)
  local function walk(list, depth, out)
    for _, step in ipairs(list) do
      if step.op == "if" then
        walk(step.yes, depth + 1, out)
        walk(step.no, depth + 1, out)
      else
        out[#out + 1] = { op = step.op, target = step.target, depth = depth }
      end
    end
  end
  local flat = {}
  walk(steps, 0, flat)
  local callSeen = false
  for _, entry in ipairs(flat) do
    if entry.op == "call" then
      callSeen = true
      Assert.equal(entry.depth, 1, "the conditional call sits inside one if")
    end
  end
  Assert.isTrue(callSeen, "the conditional call survives as a call")
end

-- 7. A label on the second instruction of a candidate fold keeps the
-- instructions separate: jumping into the fold's interior must not execute
-- the folded head.
T["fold respects interior labels"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          -- 0x20: Goto (6 bytes) -> 0x26, target 0x2C (labels the GoToIf)
          { op = 22, args = { { target = 0x2C, width = 4 } } },
          -- 0x26: compare (6 bytes) -> 0x2C
          { op = 17, args = { { value = 1, width = 2 }, { value = 2, width = 2 } } },
          -- 0x2C: GoToIf (7 bytes) -> 0x33, target 0x44 (labeled entry)
          { op = 28, args = { { value = 1, width = 1 }, { target = 0x3A, width = 4 } } },
          -- 0x33: NPCMsg (3 bytes) -> 0x36
          { op = 45, args = { { value = 97, width = 1 } } },
          -- 0x36: WaitButton (2) -> 0x38
          { op = 50, args = {} },
          -- 0x38: CloseMsg (2) -> 0x3A
          { op = 53, args = {} },
          -- 0x3A: End (2) -> 0x3C
          { op = 2, args = {} },
          -- 0x3C: Goto (6) -> 0x42, target 0x42
          { op = 22, args = { { target = 0x42, width = 4 } } },
          -- 0x42: End (2) -> 0x44
          { op = 2, args = {} },
        },
      },
    },
  })
  local _, steps = translate(bytes, 5, 0)
  -- The compare and the GoToIf stay separate instructions; the label owns
  -- the branch alone.
  local ops = {}
  local function walk(list)
    for _, step in ipairs(list) do
      if step.op == "if" then
        walk(step.yes)
        walk(step.no)
      else
        ops[#ops + 1] = step.op
      end
    end
  end
  walk(steps)
  Assert.isTrue(ops[2] == "compare" or ops[3] == "compare", "the compare survives as its own instruction")
  local controlSeen = false
  for _, op in ipairs(ops) do
    if op == "goto_if" or op == "goto_compared" then
      controlSeen = true
    end
  end
  Assert.isTrue(controlSeen, "the labeled branch survives as its own control node")
end

-- 8. MovePersonFacing (opcode 339) emits position then facing: the facing
-- side effect is a canonical operation, never diagnostic data.
T["move person facing emits position and facing"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          {
            op = 339,
            args = {
              { value = 2, width = 2 },
              { value = 684, width = 2 },
              { value = 393, width = 2 },
              { value = 0, width = 2 },
              { value = 0, width = 2 },
            },
          },
          { op = 2, args = {} },
        },
      },
    },
  })
  local _, steps = translate(bytes, 5, 0)
  Assert.equal(steps[1].op, "set_object_position")
  Assert.equal(steps[2].op, "set_object_facing")
  Assert.equal(steps[2].direction, "north")
  Assert.isNil(steps[1].sourceFacing, "no diagnostic facing field survives")
end

-- 9. The verifier runs on the final structured program: a scrub that strips
-- a step's provenance leaves the source instruction uncovered and fails.
T["verifier catches post-lowering damage"] = function()
  local bytes = labSignMember()
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 843, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  local steps = Structurer.structure(lowered, 0)
  steps[3].provenance = nil -- the say's coverage vanishes
  local report = Verifier.verifyScript(steps, ir.scripts[0], ir, lowered.omissions)
  Assert.isFalse(report.ok, "the verifier sees the final program")
end

-- 10. Every emitted step retains its source provenance: the emitted text of
-- a translated script covers every reachable instruction offset.
T["emitted steps keep provenance"] = function()
  local _, steps, report = translate(labSignMember(), 843, 0)
  Assert.isTrue(report.ok)
  for i, step in ipairs(steps) do
    if step.op ~= "label" and step.op ~= "yield_tick" then
      Assert.notNil(step.provenance, "step " .. i .. " (" .. step.op .. ") keeps provenance")
      Assert.isTrue(#step.provenance.offsets > 0)
    end
  end
end

-- 11. The touchscreen visibility and list-menu builder commands lower to
-- their own semantic operations. GetMenuChoice is an independent asynchronous
-- contextual-provider request.
T["field menu commands lower with exact semantics"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          { op = 746, args = {} },
          { op = 747, args = {} },
          { op = 748, args = { { value = 0x4001, width = 2 } } },
          {
            op = 749,
            args = {
              { value = 17, width = 1 },
              { value = 5, width = 1 },
              { value = 2, width = 1 },
              { value = 1, width = 1 },
              { value = 0x4002, width = 2 },
            },
          },
          {
            op = 750,
            args = {
              { value = 9, width = 1 },
              { value = 8, width = 1 },
              { value = 7, width = 1 },
              { value = 0, width = 1 },
              { value = 0x4003, width = 2 },
            },
          },
          {
            op = 751,
            args = {
              { value = 0x4004, width = 2 },
              { value = 0x00FF, width = 2 },
              { value = 0x8005, width = 2 },
            },
          },
          { op = 752, args = {} },
          { op = 2, args = {} },
        },
      },
    },
  })
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 5, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  Assert.equal(lowered.items[1].op, "set_auxiliary_ui_visible")
  Assert.isFalse(lowered.items[1].visible)
  Assert.equal(lowered.items[2].op, "set_auxiliary_ui_visible")
  Assert.isTrue(lowered.items[2].visible)
  Assert.equal(lowered.items[3].op, "context_choice")
  Assert.deepEqual(lowered.items[3].result, { value = "var", id = "VAR_0x4001" })
  Assert.equal(#lowered.unsupported, 0)
  Assert.deepEqual(lowered.items[4], {
    op = "menu_begin",
    messageSource = "standard",
    sourcePlacement = { system = "hgss_bottom_screen_tiles", x = 17, y = 5 },
    initialCursor = 2,
    cancellable = true,
    result = { value = "var", id = "VAR_0x4002" },
    provenance = { offsets = { 40 }, opcodes = { 749 } },
  })
  Assert.deepEqual(lowered.items[5], {
    op = "menu_begin",
    messageSource = { kind = "script", bank = 543 },
    sourcePlacement = { system = "hgss_bottom_screen_tiles", x = 9, y = 8 },
    initialCursor = 7,
    cancellable = false,
    result = { value = "var", id = "VAR_0x4003" },
    provenance = { offsets = { 48 }, opcodes = { 750 } },
  })
  Assert.deepEqual(lowered.items[6], {
    op = "menu_add",
    messageId = { value = "var", id = "VAR_0x4004" },
    vanillaMetadata = 0x00FF,
    value = { value = "var", id = "VAR_0x8005" },
    provenance = { offsets = { 56 }, opcodes = { 751 } },
  })
  Assert.deepEqual(lowered.items[7], {
    op = "menu_exec",
    provenance = { offsets = { 64 }, opcodes = { 752 } },
  })
end

-- The corpus verifier must recognize every supported field-menu lowering as
-- an intentional semantic operation rather than treating it as an uncovered
-- source instruction.
T["field menu operations verify as supported"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          { op = 746, args = {} },
          { op = 747, args = {} },
          { op = 748, args = { { value = 0x4001, width = 2 } } },
          {
            op = 749,
            args = {
              { value = 17, width = 1 },
              { value = 5, width = 1 },
              { value = 2, width = 1 },
              { value = 1, width = 1 },
              { value = 0x4002, width = 2 },
            },
          },
          {
            op = 750,
            args = {
              { value = 9, width = 1 },
              { value = 8, width = 1 },
              { value = 7, width = 1 },
              { value = 0, width = 1 },
              { value = 0x4003, width = 2 },
            },
          },
          {
            op = 751,
            args = { { value = 0x4004, width = 2 }, { value = 0x00FF, width = 2 }, { value = 0x8005, width = 2 } },
          },
          { op = 752, args = {} },
          { op = 2, args = {} },
        },
      },
    },
  })
  local _, _, report = translate(bytes, 5, 0)

  Assert.isTrue(
    report.ok,
    report.problems[1] and report.problems[1].message or "field-menu operations are verifier-supported"
  )
  Assert.equal(report.unsupportedCount, 0)
end

-- 12. Opcodes 55-58 carry their execution classifications (runtime support
-- lands atomically with each); 59/60 stay classification-free explicit
-- unsupported nodes whose operands survive lowering untouched.
T["signpost 55-58 classify while 59/60 stay unsupported"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          {
            op = 55,
            args = {
              { value = 0, width = 1 },
              { value = 1, width = 1 },
              { value = 4, width = 2 },
              { value = 0x8008, width = 2 },
            },
          },
          { op = 56, args = { { value = 2, width = 1 }, { value = 0, width = 2 } } },
          { op = 57, args = { { value = 3, width = 1 } } },
          { op = 58, args = {} },
          { op = 59, args = { { value = 0, width = 1 }, { value = 0x8008, width = 2 } } },
          { op = 60, args = { { value = 0x8008, width = 2 } } },
          { op = 2, args = {} },
        },
      },
    },
  })
  for opcode = 59, 60 do
    Assert.equal(CommandCatalog.classification(opcode), CommandCatalog.UNSUPPORTED)
    Assert.isNil(CommandCatalog.SUPPORTED[opcode], "opcode " .. opcode .. " is not marked supported")
  end
  Assert.equal(CommandCatalog.classification(55), CommandCatalog.YIELD)
  Assert.equal(CommandCatalog.classification(56), CommandCatalog.YIELD)
  Assert.equal(CommandCatalog.classification(57), CommandCatalog.YIELD)
  Assert.equal(CommandCatalog.classification(58), CommandCatalog.NATIVE_WAIT)
  Assert.isTrue(CommandCatalog.SUPPORTED[55], "opcode 55 is supported")
  Assert.isTrue(CommandCatalog.SUPPORTED[56], "opcode 56 is supported")
  Assert.isTrue(CommandCatalog.SUPPORTED[57], "opcode 57 is supported")
  Assert.isTrue(CommandCatalog.SUPPORTED[58], "opcode 58 is supported")
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 5, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  Assert.equal(#lowered.unsupported, 2)
  local expected = {
    { command = 59, originalName = "ScrCmd_TrainerTips", arguments = { 0, "VAR_SPECIAL_x8008" } },
    { command = 60, originalName = "ScrCmd_WaitSignpost", arguments = { "VAR_SPECIAL_x8008" } },
  }
  for index, contract in ipairs(expected) do
    local step = lowered.unsupported[index]
    Assert.equal(step.op, "unsupported")
    Assert.equal(step.command, contract.command)
    Assert.equal(step.originalName, contract.originalName)
    Assert.deepEqual(step.arguments, contract.arguments, "opcode " .. contract.command .. " keeps its operands")
  end
  local report = Verifier.verifyScript(Structurer.structure(lowered, 0), ir.scripts[0], ir, lowered.omissions)
  Assert.equal(report.unsupportedCount, 2)
  Assert.isFalse(report.complete)
end

-- 14. Opcode 57 (SetSignpostAction) lowers its raw command code 0..4 to the
-- exact semantic command enum, and opcode 58 (WaitSignpostAction) lowers to
-- the canonical wait node with no operands. Both verify as supported with
-- provenance; unknown codes >= 5 are malformed source and never default to
-- nop.
T["set signpost action and wait signpost action lower to canonical nodes"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          { op = 57, args = { { value = 0, width = 1 } } },
          { op = 57, args = { { value = 1, width = 1 } } },
          { op = 57, args = { { value = 2, width = 1 } } },
          { op = 57, args = { { value = 3, width = 1 } } },
          { op = 57, args = { { value = 4, width = 1 } } },
          { op = 58, args = {} },
          { op = 2, args = {} },
        },
      },
    },
  })
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 5, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  local commands = { "nop", "show", "wipe_out", "wipe_in", "hide" }
  for index, command in ipairs(commands) do
    Assert.deepEqual(lowered.items[index], {
      op = "signpost_command",
      command = command,
      provenance = { offsets = { 32 + (index - 1) * 3 }, opcodes = { 57 } },
    }, "raw command " .. (index - 1) .. " must lower to " .. command)
  end
  Assert.deepEqual(lowered.items[6], {
    op = "wait_signpost_action",
    provenance = { offsets = { 47 }, opcodes = { 58 } },
  })
  local report = Verifier.verifyScript(Structurer.structure(lowered, 0), ir.scripts[0], ir, lowered.omissions)
  Assert.isTrue(report.ok, report.problems[1] and report.problems[1].message or "signpost 57/58 must verify")
  Assert.equal(report.unsupportedCount, 0)
  Assert.isTrue(report.complete)
end

-- 15. A raw SetSignpostAction command outside the pinned 0..4 range is
-- malformed source: lowering raises instead of defaulting to nop.
T["unknown signpost action command is malformed source"] = function()
  for _, raw in ipairs({ 5, 255 }) do
    local bytes = ScriptFixture.member({
      scripts = {
        {
          offset = 0x20,
          instructions = {
            { op = 57, args = { { value = raw, width = 1 } } },
            { op = 2, args = {} },
          },
        },
      },
    })
    local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 5, "synthetic", { msgBank = 543, catalog = CATALOG }))
    local ok, err = pcall(SemanticLowering.lowerScript, ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
    Assert.isFalse(ok, "raw command " .. raw .. " must not lower silently")
    Assert.isTrue(
      tostring(err):find("signpost command", 1, true) ~= nil,
      "the malformed-command error names the signpost command, got: " .. tostring(err)
    )
  end
end

-- 13. The canonical lowering shapes for opcodes 55 and 56: the raw
-- type/map (and the unused 55 output) survive exactly as source data, the
-- message id is bank-qualified from the member, and both nodes verify as
-- supported yield boundaries with provenance.
T["direction and set signpost lower to canonical nodes"] = function()
  local bytes = ScriptFixture.member({
    scripts = {
      {
        offset = 0x20,
        instructions = {
          -- DirectionSignpost: message, type, map, unused out.
          {
            op = 55,
            args = {
              { value = 0, width = 1 },
              { value = 1, width = 1 },
              { value = 4, width = 2 },
              { value = 0x8008, width = 2 },
            },
          },
          -- SetSignpostMap: type, map.
          { op = 56, args = { { value = 2, width = 1 }, { value = 0, width = 2 } } },
          { op = 2, args = {} },
        },
      },
    },
  })
  local ir = assert(ScriptBinaryDecoder.parseMember(bytes, 5, "synthetic", { msgBank = 543, catalog = CATALOG }))
  local lowered = SemanticLowering.lowerScript(ir.scripts[0], ir, { stdCatalog = SourceCatalog.catalog() })
  Assert.deepEqual(lowered.items[1], {
    op = "signpost_direction",
    message = { message = "external", bank = 543, id = 0 },
    sourceAppearance = { game = "hgss", type = 1, map = 4 },
    sourceUnusedOut = "VAR_SPECIAL_x8008",
    provenance = { offsets = { 32 }, opcodes = { 55 } },
  })
  Assert.deepEqual(lowered.items[2], {
    op = "signpost_set",
    sourceAppearance = { game = "hgss", type = 2, map = 0 },
    provenance = { offsets = { 40 }, opcodes = { 56 } },
  })
  local report = Verifier.verifyScript(Structurer.structure(lowered, 0), ir.scripts[0], ir, lowered.omissions)
  Assert.isTrue(report.ok, report.problems[1] and report.problems[1].message or "signpost 55/56 must verify")
  Assert.equal(report.unsupportedCount, 0)
  Assert.isTrue(report.complete)
end

return { tests = T }
