-- Production-composed contract for RGB555 decoder integration. The Field UI
-- manifest is generated by romdump decoders (G2dDecoder for signpost palettes,
-- FieldFontDecoder for font palettes) using RGB555 word -> 8-bit RGB conversion.
-- The correct Nintendo DS RGB555 bit layout is red bits 0..4, green 5..9, blue 10..14.
-- This test verifies that the runtime boots successfully and loads a valid manifest
-- through the production composition, without crashing due to decoder errors.
-- Detailed color correctness tests live in the romdump component layer.

local Assert = require("tests.support.Assert")
local AcceptanceHarness = require("tests.acceptance.support.AcceptanceHarness")

local T = {
  metadata = {
    capabilities = { "rom_dump", "derived_cache" },
    tags = { "field", "codec", "rom_conformance", "hgss" },
  },
  tests = {},
}

local function withGame(fn)
  local game = AcceptanceHarness.new():boot({
    versionId = "heartgold",
    map = "MAP_BURNED_TOWER_1F",
    save = "fresh",
  })
  local ok, err = xpcall(function()
    fn(game)
    Assert.equal(game:renderAttempts(), 0)
  end, debug.traceback)
  game:close()
  if not ok then
    error(err, 0)
  end
end

-- Verify that the field runtime boots successfully with the ROM-generated
-- UI manifest. The decoders (G2dDecoder, FieldFontDecoder) run during cache
-- compilation and produce colors that must be valid and deserializable.
-- A catastrophic decoder error would cause boot failure before reaching here.
function T.tests.field_runtime_boots_with_generated_ui_manifest()
  withGame(function(game)
    local runtime = assert(game.runtime, "field runtime must boot successfully")
    local manifest = assert(runtime.uiManifest, "runtime must load and validate the generated UI manifest")
    Assert.notNil(manifest.signposts, "manifest must have signposts section")
  end)
end

-- Verify that the UI manifest structure is accessible and contains expected
-- sections. This proves the decoders produced valid output that passed
-- schema validation and was deserializable.
function T.tests.ui_manifest_has_expected_structure()
  withGame(function(game)
    local manifest = assert(game.runtime.uiManifest, "manifest must exist")
    Assert.notNil(manifest.startMenu, "manifest must have startMenu section")
    Assert.notNil(manifest.dialogueFrames, "manifest must have dialogueFrames section")
    Assert.notNil(manifest.signposts, "manifest must have signposts section")
    Assert.notNil(manifest.assets, "manifest must have assets section")
  end)
end

return T
