-- The single consumer-visible identity of the derived assets crossing the
-- romdump boundary: cache formats, generated schemas, and binary format
-- versions. Producers and runtime read these constants through the libs/assets
-- cache modules rather than carrying their own literals, so a format change is
-- one edit. `revision` is the manual escape hatch for a shared contract
-- behavior change that alters generated bytes without changing any schema
-- constant; compiler implementation versions are deliberately absent (producer
-- freshness belongs to the romdump source fingerprint).
--
-- revision 2: the compiled NSBTP payload drops the redundant
-- keyCount/numTextures/numPalettes counts (sampler and gate trust the
-- arrays).
--
-- fieldUi schema 5: signposts.types entries gain per-type palette banks
-- (one 16-color table per source type) and per-type frameTiles rectangles.
-- The old global signposts.frame.tiles authority is removed. Each type's
-- frame strip uses its own palette for precolored rendering.
--
-- fieldUi schema 4: the manifest drops the per-frame dialogueFrames.palettes
-- records (the palette colors are baked into the compiled frame-strip PNG;
-- no runtime consumer exists).
--
-- fieldUi schema 3: signpost wayfinding becomes a per-(type,map) rect table
-- (signposts.types[N].wayfinding[map]) and the manifest drops the
-- startMenu.icons mapping (no runtime consumer remains; the icon art is
-- baked into the background surface).
--
-- fieldUi schema 2: the generated field-UI manifest drops the sounds
-- section (the branch no longer compiles Start Menu effects).
--
-- messages cacheFormat v2: YESNO tokens classify as focus_indicator in the
-- persisted bank streams (runtime playback rejects the old
-- unsupported_control classification), so a stale bank must not be misread.
--
-- font cacheFormat/schema v2: the compiled definition gains seven color bands
-- and a focus-indicator PNG, and the marker hashes font member 6, so a stale
-- pre-change font cache must not pass readiness.

local DerivedAssetContract = {}

DerivedAssetContract.revision = 2

DerivedAssetContract.map = {
  cacheFormat = "map-cache-v7",
  -- v6: render-state extension over v5 — scenes carry the real HGSS field
  -- edge-color table (scene.edgeColors), every batch/material record carries
  -- the per-polygon fog gate (fogEnabled, PolygonState.FIELDS), and scenes
  -- carry the map's base weather ID plus its resolved global HGSS fog preset
  -- (scene.weatherId, scene.fog).
  sceneSchema = "g4-map-scene-v6",
  terrainSchema = "g4-terrain-surfaces-v1",
  collisionVersion = 1,
}

DerivedAssetContract.fieldActors = {
  cacheFormat = "field-actor-cache-v1",
  schema = "g4-field-actor-v1",
  indexSchema = "g4-field-actor-index-v1",
}

DerivedAssetContract.fieldCamera = {
  cacheFormat = "g4-field-camera-cache-v1",
  schema = "g4-field-camera-profiles-v1",
}

DerivedAssetContract.fieldMapData = {
  cacheFormat = "g4-field-map-cache-v1",
  fieldSchema = "g4-field-map-v1",
}

DerivedAssetContract.messages = {
  cacheFormat = "field-message-cache-v2",
  schema = "g4-field-message-bank-v1",
  indexSchema = "g4-field-message-index-v1",
  provenanceSchema = "g4-field-message-provenance-v1",
}

DerivedAssetContract.font = {
  cacheFormat = "field-font-cache-v2",
  schema = "g4-field-font-v2",
}

DerivedAssetContract.scripts = {
  cacheFormat = "script-cache-v1",
  indexSchema = "g4-script-index-v1",
  provenanceSchema = "g4-script-provenance-v1",
}

DerivedAssetContract.fieldUi = {
  cacheFormat = "field-ui-cache-v1",
  schema = "g4-field-ui-v5",
}

-- The mesh batch format constants (magic, version, stride, header size,
-- index widths) have their own owner (G4MeshFormat); the vertex-layout
-- version aliases that owner's version, so nothing mesh-shaped lives here.

return DerivedAssetContract
