-- The single consumer-visible identity of the derived assets crossing the
-- romdump boundary: cache formats, generated schemas, and binary format
-- versions. Producers and runtime read these constants through the libs/assets
-- cache modules rather than carrying their own literals, so a format change is
-- one edit. `revision` is the manual escape hatch for a shared contract
-- behavior change that alters generated bytes without changing any schema
-- constant; compiler implementation versions are deliberately absent (producer
-- freshness belongs to the romdump source fingerprint).
--
-- revision 2: the compiled NSBTP payload drops the redundant
-- keyCount/numTextures/numPalettes counts (sampler and gate trust the
-- arrays).

local DerivedAssetContract = {}

DerivedAssetContract.revision = 2

DerivedAssetContract.map = {
  cacheFormat = "map-cache-v7",
  -- v6: scenes carry the real HGSS field edge-color table (scene.edgeColors).
  -- v7: every batch record carries fogEnabled (PolygonState.FIELDS), the
  -- per-polygon fog gate the map shader now reads.
  sceneSchema = "g4-map-scene-v7",
  terrainSchema = "g4-terrain-surfaces-v1",
  collisionVersion = 1,
}

DerivedAssetContract.fieldActors = {
  cacheFormat = "field-actor-cache-v1",
  schema = "g4-field-actor-v1",
  indexSchema = "g4-field-actor-index-v1",
}

DerivedAssetContract.fieldCamera = {
  cacheFormat = "g4-field-camera-cache-v1",
  schema = "g4-field-camera-profiles-v1",
}

DerivedAssetContract.fieldMapData = {
  cacheFormat = "g4-field-map-cache-v1",
  fieldSchema = "g4-field-map-v1",
}

DerivedAssetContract.messages = {
  cacheFormat = "field-message-cache-v1",
  schema = "g4-field-message-bank-v1",
  indexSchema = "g4-field-message-index-v1",
  provenanceSchema = "g4-field-message-provenance-v1",
}

DerivedAssetContract.font = {
  cacheFormat = "field-font-cache-v1",
  schema = "g4-field-font-v1",
}

DerivedAssetContract.scripts = {
  cacheFormat = "script-cache-v1",
  indexSchema = "g4-script-index-v1",
  provenanceSchema = "g4-script-provenance-v1",
}

-- The mesh batch format constants (magic, version, stride, header size,
-- index widths) have their own owner (G4MeshFormat); the vertex-layout
-- version aliases that owner's version, so nothing mesh-shaped lives here.

return DerivedAssetContract
