-- Stable error codes for the engine field layer: event state, actors,
-- terrain surfaces, render-queue classification, warp resolution, and map
-- loading. Every module in this layer raises Errors with exactly these
-- codes; modules must reference the named constants, never bare literals, so
-- a rename stays in one place. The script subsystem keeps its own catalogue
-- (script/errors.lua). Pure domain module: no love dependency.

local FieldErrors = {}

FieldErrors.EVENT_STATE_TOO_LARGE = "EVENT_STATE_TOO_LARGE"
FieldErrors.EVENT_FLAG_VALUE_INVALID = "EVENT_FLAG_VALUE_INVALID"
FieldErrors.EVENT_VAR_VALUE_INVALID = "EVENT_VAR_VALUE_INVALID"
FieldErrors.EVENT_FLAG_ID_INVALID = "EVENT_FLAG_ID_INVALID"
FieldErrors.EVENT_VAR_ID_INVALID = "EVENT_VAR_ID_INVALID"

FieldErrors.RENDER_QUEUE_UNKNOWN_ALPHA_CLASS = "RENDER_QUEUE_UNKNOWN_ALPHA_CLASS"

FieldErrors.ACTOR_OCCUPANCY_CONFLICT = "ACTOR_OCCUPANCY_CONFLICT"
FieldErrors.ACTOR_FACING_INVALID = "ACTOR_FACING_INVALID"
FieldErrors.ACTOR_VISUAL_MISSING = "ACTOR_VISUAL_MISSING"
FieldErrors.ACTOR_DUPLICATE_ID = "ACTOR_DUPLICATE_ID"
FieldErrors.ACTOR_POSE_DIRECTION_MISSING = "ACTOR_POSE_DIRECTION_MISSING"
FieldErrors.ACTOR_POSE_MISSING = "ACTOR_POSE_MISSING"
FieldErrors.ACTOR_SURFACE_MISSING = "ACTOR_SURFACE_MISSING"
FieldErrors.ACTOR_SURFACE_AMBIGUOUS = "ACTOR_SURFACE_AMBIGUOUS"

FieldErrors.TERRAIN_SURFACE_NOT_FOUND = "TERRAIN_SURFACE_NOT_FOUND"
FieldErrors.TERRAIN_SURFACE_AMBIGUOUS = "TERRAIN_SURFACE_AMBIGUOUS"
FieldErrors.TERRAIN_SURFACE_DISCONNECTED = "TERRAIN_SURFACE_DISCONNECTED"

FieldErrors.FIELD_MAP_UNKNOWN = "FIELD_MAP_UNKNOWN"
FieldErrors.FIELD_DESTINATION_MAP_UNKNOWN = "FIELD_DESTINATION_MAP_UNKNOWN"
FieldErrors.FIELD_DESTINATION_WARP_UNKNOWN = "FIELD_DESTINATION_WARP_UNKNOWN"
FieldErrors.FIELD_DYNAMIC_WARP_UNSUPPORTED = "FIELD_DYNAMIC_WARP_UNSUPPORTED"
FieldErrors.FIELD_MAP_VISUAL_CACHE_MISSING = "FIELD_MAP_VISUAL_CACHE_MISSING"
FieldErrors.FIELD_MAP_DATA_CACHE_MISSING = "FIELD_MAP_DATA_CACHE_MISSING"
FieldErrors.FIELD_MAP_TERRAIN_CACHE_MISSING = "FIELD_MAP_TERRAIN_CACHE_MISSING"
FieldErrors.FIELD_MAP_VISUAL_CACHE_INVALID = "FIELD_MAP_VISUAL_CACHE_INVALID"
FieldErrors.FIELD_MAP_DATA_CACHE_INVALID = "FIELD_MAP_DATA_CACHE_INVALID"
FieldErrors.FIELD_MAP_TERRAIN_CACHE_INVALID = "FIELD_MAP_TERRAIN_CACHE_INVALID"
FieldErrors.FIELD_MAP_NEIGHBOR_CACHE_MISSING = "FIELD_MAP_NEIGHBOR_CACHE_MISSING"
FieldErrors.FIELD_MAP_COLLISION_CACHE_MISSING = "FIELD_MAP_COLLISION_CACHE_MISSING"
FieldErrors.FIELD_MAP_CAMERA_MISMATCH = "FIELD_MAP_CAMERA_MISMATCH"

return FieldErrors
