-- Stable error codes for the field-script platform. The names below are frozen
-- by the sprint spec section 39 as the initial public diagnostic vocabulary;
-- every subsystem (validator, compiler, registry, scheduler, tasks, save,
-- translator) raises Errors with exactly these codes. New codes may only be
-- added, never renamed.

local Errors = {}

Errors.SCRIPT_SCHEMA_INVALID = "SCRIPT_SCHEMA_INVALID"
Errors.SCRIPT_API_UNSUPPORTED = "SCRIPT_API_UNSUPPORTED"
Errors.SCRIPT_DUPLICATE_ID = "SCRIPT_DUPLICATE_ID"
Errors.SCRIPT_UNKNOWN_OPERATION = "SCRIPT_UNKNOWN_OPERATION"
Errors.SCRIPT_INVALID_REFERENCE = "SCRIPT_INVALID_REFERENCE"
Errors.SCRIPT_CALL_TARGET_MISSING = "SCRIPT_CALL_TARGET_MISSING"
Errors.SCRIPT_LABEL_MISSING = "SCRIPT_LABEL_MISSING"
Errors.SCRIPT_UNSUPPORTED_REACHABLE = "SCRIPT_UNSUPPORTED_REACHABLE"
Errors.SCRIPT_STEP_BUDGET_EXCEEDED = "SCRIPT_STEP_BUDGET_EXCEEDED"
Errors.SCRIPT_CONTEXT_SLOTS_EXHAUSTED = "SCRIPT_CONTEXT_SLOTS_EXHAUSTED"
Errors.SCRIPT_TASK_CREATION_TICK_POLL = "SCRIPT_TASK_CREATION_TICK_POLL"
Errors.SCRIPT_TASK_DOUBLE_POLL = "SCRIPT_TASK_DOUBLE_POLL"
Errors.SCRIPT_TASK_RESULT_MISSING = "SCRIPT_TASK_RESULT_MISSING"
Errors.SCRIPT_CALLER_SIGNAL_INVALID = "SCRIPT_CALLER_SIGNAL_INVALID"
Errors.SCRIPT_TIMING_CLASSIFICATION_MISSING = "SCRIPT_TIMING_CLASSIFICATION_MISSING"
Errors.SCRIPT_LOCK_NOT_OWNED = "SCRIPT_LOCK_NOT_OWNED"
Errors.SCRIPT_ACTOR_NOT_FOUND = "SCRIPT_ACTOR_NOT_FOUND"
Errors.SCRIPT_ACTOR_BUSY = "SCRIPT_ACTOR_BUSY"
Errors.SCRIPT_BACKGROUND_FORBIDDEN = "SCRIPT_BACKGROUND_FORBIDDEN"
Errors.SCRIPT_RAW_MODULE_NOT_FOUND = "SCRIPT_RAW_MODULE_NOT_FOUND"
Errors.SCRIPT_RAW_FUNCTION_NOT_FOUND = "SCRIPT_RAW_FUNCTION_NOT_FOUND"
Errors.SCRIPT_RAW_HANDLER_ERROR = "SCRIPT_RAW_HANDLER_ERROR"
Errors.SCRIPT_RAW_HANDLER_YIELDED = "SCRIPT_RAW_HANDLER_YIELDED"
Errors.SCRIPT_RAW_RESULT_INVALID = "SCRIPT_RAW_RESULT_INVALID"
Errors.SCRIPT_TASK_UNKNOWN = "SCRIPT_TASK_UNKNOWN"
Errors.SCRIPT_TASK_VERSION_UNSUPPORTED = "SCRIPT_TASK_VERSION_UNSUPPORTED"
Errors.SCRIPT_TASK_UNSERIALIZABLE = "SCRIPT_TASK_UNSERIALIZABLE"
Errors.SCRIPT_SAVE_REVISION_MISMATCH = "SCRIPT_SAVE_REVISION_MISMATCH"
Errors.SCRIPT_REGISTRY_FINGERPRINT_MISMATCH = "SCRIPT_REGISTRY_FINGERPRINT_MISMATCH"
Errors.SCRIPT_REPLACE_CONFLICT = "SCRIPT_REPLACE_CONFLICT"
Errors.SCRIPT_WRAPPER_INVALID = "SCRIPT_WRAPPER_INVALID"
Errors.SCRIPT_HOT_RELOAD_FAILED = "SCRIPT_HOT_RELOAD_FAILED"
Errors.SCRIPT_TRANSLATION_MALFORMED = "SCRIPT_TRANSLATION_MALFORMED"
Errors.SCRIPT_TRANSLATION_UNSUPPORTED = "SCRIPT_TRANSLATION_UNSUPPORTED"
Errors.SCRIPT_TRANSLATION_VERIFY_FAILED = "SCRIPT_TRANSLATION_VERIFY_FAILED"
Errors.SCRIPT_HANDWRITTEN_STATE_UNSUPPORTED = "SCRIPT_HANDWRITTEN_STATE_UNSUPPORTED"

return Errors
