-- Developer-only synchronizer (spec §11.3). Regenerates
-- data/manifests/narc_catalog.lua from a local pret/pokeheartgold checkout by
-- parsing the NarcId enum and the sNarcFileList paths in
-- include/filesystem_files_def.h. It is NEVER required at runtime and never
-- invokes Git: the decomp root and source commit are passed in explicitly, so a
-- decomp checkout is not a contributor prerequisite.
--
-- Run:  luajit tools/sync_narc_catalog.lua <decomp-root> <commit> [out-path]
-- The module also returns { parse, render, sync } so the parser is unit tested.
--
-- Parsing invariants (asserted, not silently repaired): enum values are
-- contiguous from zero in declaration order, and the enum count equals the path
-- count. Symbols and paths are preserved exactly; sNarcFileList[i] is the path
-- for NarcId i, so the two files are zipped by index.

local M = {}

local DEF_FILE = "include/filesystem_files_def.h"

-- Extract the text between an opening marker and the first `};` after it.
local function block(source, openPattern)
  local s = source:find(openPattern)
  assert(s, "could not find block: " .. openPattern)
  local e = source:find("};", s, true)
  assert(e, "unterminated block: " .. openPattern)
  return source:sub(s, e)
end

-- Parse the enum + path array into an ordered list of { symbol, narcId, path }.
function M.parse(source)
  local enumBlock = block(source, "enum NarcId%s*{")
  local symbols = {}
  for symbol, value in enumBlock:gmatch("(NARC_[%w_]+)%s*=%s*(%d+)") do
    local narcId = tonumber(value)
    assert(narcId == #symbols, "NarcId enum is not contiguous from zero: expected "
      .. #symbols .. ", got " .. narcId .. " for " .. symbol)
    symbols[#symbols + 1] = symbol
  end
  assert(#symbols > 0, "no NARC_* enum members found")

  local listBlock = block(source, "sNarcFileList%[%]%s*=%s*{")
  local paths = {}
  for path in listBlock:gmatch('"([^"]*)"') do
    paths[#paths + 1] = path
  end

  assert(#symbols == #paths,
    "enum count " .. #symbols .. " != path count " .. #paths)

  local entries = {}
  for i = 1, #symbols do
    entries[i] = { symbol = symbols[i], narcId = i - 1, path = paths[i] }
  end
  return entries
end

-- Render the deterministic narc_catalog.lua text. Entries are emitted one per
-- line ascending by narcId, matching the checked-in curated file's style.
function M.render(entries, commit)
  assert(type(commit) == "string" and commit ~= "", "a source commit is required")
  local out = {
    "-- Decompilation-derived NARC catalog: maps each NARC symbol to its NarcId enum",
    "-- value and physical NitroFS path. Auto-generated by tools/sync_narc_catalog.lua;",
    "-- do not edit by hand (spec §11.3). Pure data, no runtime dependencies.",
    "--",
    "-- narcId is the index into HGSS's NarcId enum / sNarcFileList; it is NOT a FAT",
    "-- fileId. `path` is resolved to a fileId through the parsed FNT at import time.",
    "",
    "return {",
    "  schema = 1,",
    "  source = {",
    '    repo = "pret/pokeheartgold",',
    string.format("    commit = %q,", commit),
    string.format("    files = { %q },", DEF_FILE),
    '    note = "Full NarcId enum. Regenerate with tools/sync_narc_catalog.lua.",',
    "  },",
    "  entries = {",
  }
  for _, e in ipairs(entries) do
    out[#out + 1] = string.format("    %s = { narcId = %d, path = %q },",
      e.symbol, e.narcId, e.path)
  end
  out[#out + 1] = "  },"
  out[#out + 1] = "}"
  out[#out + 1] = ""
  return table.concat(out, "\n")
end

-- Read the decomp header, parse, render, and write the catalog. opts:
-- { decompRoot=, commit=, out= }. Pure io (no love, no Git).
function M.sync(opts)
  local defPath = opts.decompRoot .. "/" .. DEF_FILE
  local f = assert(io.open(defPath, "r"), "cannot open " .. defPath)
  local source = f:read("*a")
  f:close()

  local entries = M.parse(source)
  local text = M.render(entries, opts.commit)

  local outPath = opts.out or "data/manifests/narc_catalog.lua"
  local o = assert(io.open(outPath, "w"), "cannot write " .. outPath)
  o:write(text)
  o:close()
  return { count = #entries, out = outPath }
end

local function main(argv)
  local decompRoot, commit, out = argv[1], argv[2], argv[3]
  if not decompRoot or not commit then
    io.stderr:write("usage: luajit tools/sync_narc_catalog.lua <decomp-root> <commit> [out-path]\n")
    os.exit(2)
  end
  local result = M.sync({ decompRoot = decompRoot, commit = commit, out = out })
  print(string.format("wrote %d entries to %s (commit %s)", result.count, result.out, commit))
end

-- Run as a script (luajit) but stay inert when required as a module.
if arg and arg[0] and arg[0]:find("sync_narc_catalog") then
  main(arg)
end

return M
